### ISSUE TITLE
[Task Assignment]: Web Speech API Implementation

### ISSUE THREAD

**Issue by ankman007** [org-45/yantra-lite#6]
### Task Description
Implement a web development project using HTML, CSS, and JavaScript that integrates or utilizes a Web Speech API. Your project should demonstrate your understanding of integrating APIs into web applications.

### Task Requirements

- Directory Creation: Create a new directory inside the "participants" folder with your name as the directory name.
![directory example](https://github.com/org-45/yantra-lite/assets/108212023/61ec8a12-4ea3-4277-9d35-2bfd17a6b202)

- File Creation: Inside your newly created directory, create all necessary files for your project, including HTML, CSS, and JavaScript files.
![file example](https://github.com/org-45/yantra-lite/assets/108212023/064e1bdb-1429-4c14-83db-14f52936a8a5)

- API Integration: Implement the Web Speech API of your choice into your project. Ensure the API is functional and provides meaningful results.
- Navigation Update: In the bootcamp.html file, append a new list item under the <navigation> tag with your name and a link to the directory you've created. Ensure the navigation item is styled appropriately.
![name example](https://github.com/org-45/yantra-lite/assets/108212023/33f126b0-b00d-4a65-a7e8-4ae845145cd8)

### Submission Guidelines

- Branch Creation: Create a new branch for your work: git checkout -b feature/your-feature-name
- Commit Changes: Commit your changes with a descriptive message: git commit -m "Description of changes"
- Push to Your Branch: Push the changes to your branch: git push origin feature/your-feature-name
- Pull Request: Create a Pull Request to merge your changes into the main branch.

### Additional Guidelines
- Code Quality: Ensure your code is well-organized, readable, and follows best practices.
- Error Handling: Implement appropriate error handling for API responses and user interactions.
- Testing: Test your application thoroughly to ensure it functions as expected.
- Documentation: Document any external APIs used, along with instructions on how to run your project locally.

### Resources and References
Web Speech API Documentation: [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API)

**Comment by krishnemd** [comment]
@ankman007 Just checked your PR. 
Can you make a separate PR stating on h4 "Please talk for your voice to get transcribed" or something like that ?
