### ISSUE TITLE
[Task Assignment]: Clipboard API Implementation

### ISSUE THREAD

**Issue by ankman007** [org-45/yantra-lite#8]
### Task Description
Implement a web project using HTML, CSS, and JavaScript that integrates a Clipboard API.

### Task Requirements

- Create a new directory inside "participants" with your name.
- Develop necessary HTML, CSS, and JavaScript files.
- Integrate a Clipboard API into your project.
- Update bootcamp.html with your name under `<navigation>`

### Submission Guidelines

- Create a branch: git checkout -b feature/your-feature-name
- Commit changes: git commit -m "Description of changes"
- Push to branch: git push origin feature/your-feature-name
- Create a Pull Request to merge changes into main.

### Additional Guidelines

- Maintain code quality and organization.
- Implement error handling and thorough testing.
- Document external APIs used.

### Resources
[Clipboard API Documentation](https://developer.mozilla.org/en-US/docs/Web/API/clipboard)

**Comment by manjilkoirala** [comment]
Something went wrong so i deleted the branch and created new pull request #12
