### ISSUE TITLE
[Task Assignment]: Geolocation API Implementation

### ISSUE THREAD

**Issue by ankman007** [org-45/yantra-lite#9]
### Task Description
Implement a web project using HTML, CSS, and JavaScript that integrates a Geolocation API.

### Task Requirements

- Create a new directory inside "participants" with your name.
- Develop necessary HTML, CSS, and JavaScript files.
- Integrate a Geolocation API into your project.
- Update bootcamp.html with your name under `<navigation>`

### Submission Guidelines

- Create a branch: git checkout -b feature/your-feature-name
- Commit changes: git commit -m "Description of changes"
- Push to branch: git push origin feature/your-feature-name
- Create a Pull Request to merge changes into main.

### Additional Guidelines

- Maintain code quality and organization.
- Implement error handling and thorough testing.
- Document external APIs used.

### Resources
[Geolocation API Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API)

**Comment by manjilkoirala** [comment]
Issue fixes.
